# Generated by Django 3.0.5 on 2020-06-12 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('internshipDuration', models.IntegerField(verbose_name='Staj Süresi')),
                ('startDate', models.DateField(verbose_name='Staj Başlangıç Tarihi')),
                ('finishDate', models.DateField(verbose_name='Staj Bitiş Tarihi')),
                ('catchment', models.CharField(max_length=60, verbose_name='Hizmet Alanı')),
                ('companyPhoneNum', phone_field.models.PhoneField(max_length=31, verbose_name='Firma Telefon')),
                ('companyMentorName', models.CharField(max_length=120, verbose_name='Firma İlgili Kişi')),
                ('email', models.EmailField(max_length=120, verbose_name='E-posta Adresi')),
                ('companyAddress', models.TextField(max_length=300, verbose_name='Staj Adresi')),
                ('numberOfEngineers', models.IntegerField(verbose_name='Çalışan Mühendis Sayısı')),
                ('internshipType', models.CharField(choices=[('Akademik', 'Akademik'), ('Endüstriyel', 'Endüstriyel')], max_length=20, verbose_name='Staj Tipi')),
                ('internshipAbroadOrDomestic', models.CharField(choices=[('Yurt Dışı', 'Yurt Dışı'), ('Yurt İçi', 'Yurt İçi')], max_length=20, verbose_name='Yurtiçi / Yurtdışı Staj')),
                ('companyCountry', django_countries.fields.CountryField(default='TR', max_length=2, verbose_name='Stajın Yapıldığı Ülke')),
            ],
            options={
                'verbose_name': 'Staj',
                'verbose_name_plural': 'Stajlar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcNum', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('[0-9]', 'Only numeric characters are allowed.')], verbose_name='T.C. Numarası')),
                ('studentName', models.CharField(max_length=60, verbose_name='Öğrenci Adı')),
                ('studentSurname', models.CharField(max_length=60, verbose_name='Öğrenci Soyadı')),
                ('studentNum', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator('[0-9]', 'Only numeric characters are allowed.')], verbose_name='Öğrenci Numarası')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
        migrations.CreateModel(
            name='InternShipHiddenFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internshipDevamNotu', models.IntegerField(verbose_name='Staj Devam Notu')),
                ('internshipCalismaNotu', models.IntegerField(verbose_name='Çalışma Ve Gayret Notu')),
                ('internshipZamanNotu', models.IntegerField(verbose_name='İşi Zamanında ve Tam Yapma Notu')),
                ('internshipAmirNotu', models.IntegerField(verbose_name='Amirine Karşı Tutumu Notu')),
                ('internshipArkadas', models.IntegerField(verbose_name='İşçi ve Arkadaşlarına Karşı Tutumu Notu')),
                ('internshipDiger', models.ImageField(upload_to='uploads/', verbose_name='Değerlendirme Formu')),
                ('firmaDegerlendirme', models.CharField(choices=[('Olumlu', 'Olumlu'), ('Olumsuz', 'Olumsuz')], max_length=20, verbose_name='Firma Değerlendirme')),
                ('firmaYorumu', models.TextField(verbose_name='Firma Yorumu')),
                ('notOrtalaması', models.IntegerField(blank=True, verbose_name='Not Ortalaması')),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.InternShip', verbose_name='Şirket Adı')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'verbose_name': 'Staj Bilgileri(Gizli İçerik)',
            },
        ),
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
