# Generated by Django 3.0.5 on 2020-06-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={'verbose_name': 'Staj', 'verbose_name_plural': 'Stajlar'},
        ),
        migrations.AlterModelOptions(
            name='internshiphiddenfields',
            options={'verbose_name': 'Staj Bilgileri(Gizli İçerik)'},
        ),
        migrations.AlterField(
            model_name='internshiphiddenfields',
            name='firmaDegerlendirme',
            field=models.CharField(choices=[('Olumlu', 'Olumlu'), ('Olumsuz', 'Olumsuz')], max_length=20, verbose_name='Firma Değerlendirme'),
        ),
    ]
