# Generated by Django 3.0.5 on 2020-06-08 17:53

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='catchment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='companyAddress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='companyCountry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='companyMentorName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='companyPhoneNum',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='finishDate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internshipAbroadOrDomestic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internshipDuration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internshipType',
        ),
        migrations.RemoveField(
            model_name='student',
            name='numberOfEngineers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='startDate',
        ),
        migrations.CreateModel(
            name='InternShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('internshipDuration', models.IntegerField(verbose_name='Staj Süresi')),
                ('startDate', models.DateField(verbose_name='Staj Başlangıç Tarihi')),
                ('finishDate', models.DateField(verbose_name='Staj Bitiş Tarihi')),
                ('catchment', models.CharField(max_length=60, verbose_name='Hizmet Alanı')),
                ('companyPhoneNum', phone_field.models.PhoneField(max_length=31, verbose_name='Firma Telefon')),
                ('companyMentorName', models.CharField(max_length=120, verbose_name='Firma İlgili Kişi')),
                ('email', models.EmailField(max_length=120, verbose_name='E-posta Adresi')),
                ('companyAddress', models.TextField(max_length=300, verbose_name='Staj Adresi')),
                ('numberOfEngineers', models.IntegerField(verbose_name='Çalışan Mühendis Sayısı')),
                ('internshipType', models.CharField(choices=[('Akademik', 'Akademik'), ('Endüstriyel', 'Endüstriyel')], max_length=20, verbose_name='Staj Tipi')),
                ('internshipAbroadOrDomestic', models.CharField(choices=[('Yurt Dışı', 'Yurt Dışı'), ('Yurt İçi', 'Yurt İçi')], max_length=20, verbose_name='Yurtiçi / Yurtdışı Staj')),
                ('companyCountry', django_countries.fields.CountryField(default='TR', max_length=2, verbose_name='Stajın Yapıldığı Ülke')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Öğrenci')),
            ],
        ),
    ]
