# Generated by Django 3.0.5 on 2020-06-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200608_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='student',
        ),
    ]
