# Generated by Django 3.0.5 on 2020-06-10 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200611_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshiphiddenfields',
            name='internship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.InternShip', verbose_name='Şirket Adı'),
        ),
    ]
