# Generated by Django 3.0.5 on 2020-06-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200609_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshiphiddenfields',
            old_name='internship',
            new_name='student',
        ),
    ]
