# Generated by Django 3.0.5 on 2020-06-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200609_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={},
        ),
    ]
