# Generated by Django 3.0.5 on 2020-06-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200609_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternShipHiddenFields',
        ),
    ]
